########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 8/2/2016
#
# Generic Gcc Makefile for xene xene Executable
########################################################################

#
# Executable C++ .cpp sources
#
xene_EXE_CPP_SOURCES += \
${XENE_SRC}/xene/xml/libxml2/libxslt/processor.cpp \
${XENE_SRC}/xene/xml/libxml2/libxslt/parameters.cpp \
${XENE_SRC}/xene/xml/libxml2/libxslt/parameter.cpp \
${XENE_SRC}/xene/xml/xslt/extension_module.cpp \
${XENE_SRC}/xene/xml/xslt/extension_function.cpp \
${XENE_SRC}/xene/xml/xslt/stylesheet.cpp \
${XENE_SRC}/xene/xml/xslt/document.cpp \
${XENE_SRC}/xene/xml/character_writer.cpp \
${XENE_SRC}/xene/xml/character_reader.cpp \
${XENE_SRC}/xene/xml/character_string.cpp \
${XENE_SRC}/xene/xml/character.cpp \

xene_EXE_CPP_SOURCES += \
${XENE_SRC}/xene/app/console/xene/main.cpp \
${XENE_SRC}/xene/console/main_opt.cpp \
${XENE_SRC}/xene/console/main_main.cpp \

xene_EXE_CPP_SOURCES += \
${XENE_SRC}/xene/io/logger.cpp \
${XENE_SRC}/xene/io/writer.cpp \
${XENE_SRC}/xene/io/reader.cpp \
${XENE_SRC}/xene/base/base.cpp \
