########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 8/2/2016
#
# Generic Gcc Makefile for xene libxene Library
########################################################################

#
# user c++ flags
#
libxene_USRCXXFLAGS += \
${xene_USRCXXFLAGS} \

#
# user defines
#
libxene_USRDEFINES = \
${xene_USRDEFINES} \

#
# user includes
#
libxene_USRINCLUDES = \
${xene_USRINCLUDES} \

#
# user libdirs
#
libxene_USRLIBDIRS = \
${xene_USRLIBDIRS} \

#
# C .c sources
#
libxene_LIB_C_SOURCES = \

#
# C++ .cxx sources
#
libxene_LIB_CXX_SOURCES = \

#
# C++ .cpp sources
#
libxene_LIB_CPP_SOURCES += \
${XENE_SRC}/xene/base/base.cpp \

#
# libs
#
libxene_LIBS = \
-lxene \
${xene_LIBS} \

